cayzlh:
  framework:
    jwt:
      secret: 123456789
      issuer: cayzlh
      subject: token
      audience: users
      redis-check: true
      single-login: true
      salt-check: true
    shiro:
      enable: true
      anon:
        - /app/login
spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    password:
    timeout: 180000