server:
  port: 8081
cayzlh:
  framework:
    base:
      log:
        level: INFO
        path: logs
        enable: true
        exclude-paths: /xxx
        request-log-format: true
        response-log-format: true
      convertable: true