server:
  port: 8081
cayzlh:
  framework:
    base:
      log:
        level: INFO
        path: logs
        enable: true
        exclude-paths: /xxx
        request-log-format: true
        response-log-format: true
      swagger:
        enable: true
        base-package: com.cayzlh.framewrok.base.sample.controller;
      project-name: ${spring.application.name}
spring:
  application:
    name: base-sample-demo